name: 5-minute-cron
# custom:
  # secrets: ${file(secrets.yml):${self:provider.stage}}
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://tio-jorge-website.vercel.app/api/cronJob' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
